# Generated by Django 3.0.8 on 2021-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='タイトル'),
        ),
    ]
