# Generated by Django 3.0.8 on 2021-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='discription',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
