# Generated by Django 3.1.5 on 2021-04-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0003_auto_20210404_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_publick',
            field=models.BooleanField(default=False, help_text='公開する場合はチェックを入れてください', verbose_name='公開する'),
        ),
    ]
