# Generated by Django 3.0.8 on 2021-04-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0004_blog_is_publick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_publick',
            new_name='is_public',
        ),
    ]
