# Generated by Django 3.1.5 on 2021-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0005_auto_20210404_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '記事カテゴリー',
                'verbose_name_plural': '記事カテゴリー',
                'db_table': 'BlogCategory',
            },
        ),
    ]
