# Generated by Django 3.1.5 on 2021-04-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0008_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
