# Generated by Django 3.1.5 on 2021-04-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0009_blogcategory_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='media_service.BlogCategory'),
        ),
    ]
