"""
Django settings for zissyu_navi project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import environ
from .base import *

env = environ.Env()
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env.read_env(os.path.join(BASE_DIR,'.env'))

SECRET_KEY = env('SECRET_KEY')

DEBUG = False

ALLOWED_HOSTS = ['hospeee.com','188.166.190.15']

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mysite',
        'USER':'mysiteuser',
        'PASSWORD':'mysiteuserp@S5',
        'HOST':'localhost',
        'PORT':'5432',
        'ATOMIC_REQUESTS':True,
    }
}

STATIC_URL = '/static/'
STATICFILES_DIRS = (
            os.path.join(BASE_DIR, 'static'),
            )
STATIC_ROOT = '/var/www/mysite'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/mysite/media'

####################
## Email Settings ##
####################
EMAIL_BACKEND       = "sendgrid_backend.SendgridBackend"
SENDGRID_API_KEY    = env('SENDGRID_APIKEY')

SENDGRID_SANDBOX_MODE_IN_DEBUG = False
