# Generated by Django 3.0.8 on 2021-01-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='Record',
        ),
    ]
