# Generated by Django 3.0.8 on 2021-01-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_record_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], help_text='性別', null=True),
        ),
    ]
