# Generated by Django 3.0.8 on 2021-01-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210129_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='hospital_name',
            field=models.CharField(help_text='○○病院', max_length=100, verbose_name='病院名'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], help_text='性別', null=True, verbose_name='性別'),
        ),
    ]
