# Generated by Django 3.0.8 on 2021-01-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210129_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.IntegerField(help_text='実習年度', null=True, verbose_name='実習年度'),
        ),
    ]
