# Generated by Django 3.0.8 on 2021-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_record_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='major',
            field=models.CharField(choices=[('医師', '医師'), ('看護師', '看護師')], help_text='専攻', max_length=100, null=True, verbose_name='専攻'),
        ),
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.IntegerField(null=True, verbose_name='実習年度'),
        ),
    ]
