# Generated by Django 3.0.8 on 2021-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210129_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sex',
            field=models.IntegerField(choices=[('男', '男'), ('女', '女')], help_text='性別', null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.CharField(max_length=100, null=True, verbose_name='実習年度'),
        ),
    ]
