# Generated by Django 3.0.8 on 2021-01-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210129_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='url',
            field=models.URLField(help_text='ホームページURL', null=True, verbose_name='ホームページURL'),
        ),
        migrations.AlterField(
            model_name='record',
            name='major',
            field=models.CharField(choices=[('医師', '医師'), ('看護師', '看護師'), ('薬剤師', '薬剤師'), ('理学療法士', '理学療法士'), ('歯科医師', '歯科医師')], help_text='専攻', max_length=100, null=True, verbose_name='専攻'),
        ),
    ]
