# Generated by Django 3.0.8 on 2021-01-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210129_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='review',
            field=models.IntegerField(help_text='0~5', null=True, verbose_name='実習総合評価'),
        ),
        migrations.AddField(
            model_name='record',
            name='review_people',
            field=models.IntegerField(help_text='0~5', null=True, verbose_name='実習担当者について'),
        ),
        migrations.AddField(
            model_name='record',
            name='review_people_comment',
            field=models.TextField(help_text='実習担当者について感じた事・思った事', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='url',
            field=models.URLField(null=True, verbose_name='ホームページURL'),
        ),
    ]
