# Generated by Django 3.0.8 on 2021-01-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210129_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='review_people_comment',
            field=models.TextField(blank=True, help_text='実習担当者について感じた事・思った事', max_length=1000, null=True, verbose_name=''),
        ),
    ]
