# Generated by Django 3.0.8 on 2021-01-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210129_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='打刻日'),
        ),
        migrations.AddField(
            model_name='record',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='登録時刻'),
        ),
    ]
