# Generated by Django 3.1.5 on 2021-01-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20210130_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='place',
            field=models.CharField(choices=[('hokkaido', '北海道'), ('aomori', '青森'), ('iwate', '岩手'), ('akita', '秋田'), ('miyagi', '宮城'), ('yamagata', '山形'), ('fukushima', '福島'), ('ibaraki', '茨城'), ('tochigi', '栃木'), ('gunma', '群馬'), ('saitama', '埼玉'), ('chiba', '千葉'), ('tokyo', '東京'), ('kanagawa', '神奈川'), ('nigata', '新潟'), ('toyama', '富山'), ('ishikawa', '石川'), ('fukui', '福井'), ('yamanashi', '山梨'), ('nagano', '長野'), ('gihu', '岐阜'), ('shizuoka', '静岡'), ('aichi', '愛知'), ('mie', '三重'), ('shiga', '滋賀'), ('kyoto', '京都'), ('osaka', '大阪'), ('hyogo', '兵庫'), ('nara', '奈良'), ('wakayama', '和歌山'), ('tottori', '鳥取'), ('simane', '島根'), ('okayama', '岡山'), ('hiroshima', '広島'), ('yamaguchi', '山口'), ('tokushima', '徳島'), ('kagawa', '香川'), ('ehime', '愛媛'), ('kochi', '高知'), ('fukuoka', '福岡'), ('saga', '佐賀'), ('ohita', '大分'), ('miyazaki', '宮崎'), ('nagasaki', '長崎'), ('kumamoto', '熊本'), ('kagoshima', '鹿児島'), ('okinawa', '沖縄')], help_text='病院所在地', max_length=100, null=True, verbose_name='病院所在地'),
        ),
        migrations.AlterField(
            model_name='record',
            name='major',
            field=models.CharField(choices=[('doctor', '医師'), ('nurce', '看護師'), ('pharmacist', '薬剤師'), ('physical_therapist', '理学療法士'), ('dentist', '歯科医師')], help_text='専攻', max_length=100, null=True, verbose_name='専攻'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sex',
            field=models.IntegerField(choices=[('man', '男'), ('woman', '女')], help_text='性別', null=True, verbose_name='性別'),
        ),
    ]
