# Generated by Django 3.1.5 on 2021-01-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_remove_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(verbose_name='打刻日'),
        ),
    ]
