# Generated by Django 3.1.5 on 2021-01-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20210130_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='打刻日'),
        ),
    ]
