# Generated by Django 3.1.5 on 2021-01-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20210130_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sex',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], help_text='性別', max_length=100, null=True, verbose_name='性別'),
        ),
    ]
