# Generated by Django 3.1.5 on 2021-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20210130_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='件数'),
        ),
    ]
