# Generated by Django 3.1.5 on 2021-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20210130_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='db_major_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB用専攻名'),
        ),
    ]
