# Generated by Django 3.0.8 on 2021-02-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_auto_20210203_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapeter_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='章')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_tg', models.CharField(blank=True, max_length=100, null=True, verbose_name='条')),
                ('article_content', models.TextField(blank=True, max_length=100, null=True, verbose_name='規約')),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category', verbose_name='カテゴリー')),
                ('article_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Chapter', verbose_name='章')),
            ],
        ),
    ]
