# Generated by Django 3.1.5 on 2021-02-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_article_category_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapeter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
