# Generated by Django 3.1.5 on 2021-02-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_chapter_chapeter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
