# Generated by Django 3.1.5 on 2021-02-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_auto_20210205_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapeter_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='条'),
        ),
    ]
