# Generated by Django 3.1.5 on 2021-02-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_auto_20210205_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Number'),
        ),
    ]
