# Generated by Django 3.1.5 on 2021-02-06 05:04

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_auto_20210205_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=3000, null=True, verbose_name='規約本文'),
        ),
    ]
