# Generated by Django 3.1.5 on 2021-02-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_auto_20210206_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='category_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='カテゴリー'),
        ),
    ]
