# Generated by Django 3.1.5 on 2021-02-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_auto_20210206_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='規約本文'),
        ),
    ]
