# Generated by Django 3.0.8 on 2021-02-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_auto_20210206_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(max_length=5000, verbose_name='お問い合わせ内容')),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
