# Generated by Django 3.0.8 on 2021-02-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
