# Generated by Django 3.0.8 on 2021-02-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_auto_20210224_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
