# Generated by Django 3.1.5 on 2021-04-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_otherrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherrecord',
            options={'verbose_name': 'その他のクチコミ情報', 'verbose_name_plural': 'その他のクチコミ情報'},
        ),
    ]
