# Generated by Django 3.0.8 on 2021-04-13 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0070_auto_20210413_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='username',
        ),
        migrations.RemoveField(
            model_name='record',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Record'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
